branch-defaults:
  master:
    environment: four-feaq
global:
  application_name: FeatherQ Development
  default_ec2_keyname: featherq-d
  default_platform: 64bit Amazon Linux 2014.09 v1.1.0 running PHP 5.4
  default_region: ap-southeast-1
  profile: eb-cli
  sc: git
